[Release] 1.0
nf-core/quantms pull request #13
Opened 2022-03-28 17:42 UTC by jpfeuffer

Fresh PR to re-evaluate changes.

2022-03-30 12:11 UTC, ewels commented
Looks like there's a new version of the MultiQC module available 👍🏻

2022-03-30 12:39 UTC, jpfeuffer commented
> Looks like there's a new version of the MultiQC module available 👍🏻

I think we are not using it 🙈 . We added a pmultiqc nf-module. I guess because the pmultiqc mqc-module adds some additional input params to multiqc that we like to pass to the nf-module instead of doing some magic in the official multiqc module.
It would probably be possible if you have some hints on how to do it and if you think it would be nicer.
Otherwise, I would remove the multiqc module but I am already scared of the linter 😭

2022-03-31 10:29 UTC, d4straub commented on README.md
> +# ![nf-core/quantms](docs/images/nf-core/quantms_logo_light.png#gh-light-mode-only) ![nf-core/quantms](docs/images/nf-core/quantms_logo_dark.png#gh-dark-mode-only)
That is broken, please use
```suggestion
# ![nf-core/quantms](docs/images/nf-core-quantms_logo_light.png#gh-light-mode-only) ![nf-core/quantms](docs/images/nf-core-quantms_logo_dark.png#gh-dark-mode-only)
```

2022-03-31 10:32 UTC, d4straub commented on README.md
> +   nextflow run nf-core/quantms -profile test,YOURPROFILE --input project.sdrf.tsv --database protein.fasta
Since nf-core tools 2.3.x `--outdir` is required
```suggestion
   nextflow run nf-core/quantms -profile test,YOURPROFILE --input project.sdrf.tsv --database protein.fasta --outdir ./results
```

2022-03-31 10:33 UTC, d4straub commented on README.md
> +   nextflow run nf-core/quantms -profile <docker/singularity/podman/shifter/charliecloud/conda/institute> --input project.sdrf.tsv --database database.fasta
```suggestion
   nextflow run nf-core/quantms -profile <docker/singularity/podman/shifter/charliecloud/conda/institute> --input project.sdrf.tsv --database database.fasta --outdir ./results
```

2022-03-31 10:39 UTC, d4straub commented on nextflow.config
>      outdir                     = './results'
The template suggests here "null"
```suggestion
    outdir                     = null
```

2022-03-31 10:41 UTC, d4straub commented on nextflow.config
> +    acquisition_method = null
You could make that nicer (as usually recommended), i.e.
```suggestion
    input                        = null // the sdrf and spectra parameters are inferred from this one
    root_folder               = null
    local_input_type      = null
    database                 = null
    acquisition_method = null
```
also true for all entries below.

2022-03-31 10:46 UTC, d4straub commented on CHANGELOG.md
> +- First pipeline for DIA-LFQ data analsysis
this is usually amended by the PR, see e.g. https://github.com/nf-core/ampliseq/blob/dev/CHANGELOG.md
not required, just commenting!

2022-03-31 10:48 UTC, d4straub commented on README.md
> +DDA-LFQ:
This part and following might be also very well described by a graphical overview, e.g. https://nf-co.re/eager#functionality-overview
Also just a comment ;)

2022-03-31 10:53 UTC, d4straub commented on conf/test_dia.config
> +    config_profile_description = 'Minimal test dataset to check pipeline function'
Well, this test profile seems to have a specific purpose beyond test.config?

2022-03-31 10:54 UTC, d4straub commented on conf/test_dia.config
> + *   nextflow run nf-core/quantms -profile test,<docker/singularity/podman>
if you use `outdir = null` above, than better specify throughout `--outdir <OUTDIR>`

2022-03-31 11:01 UTC, d4straub commented on docs/output.md
> +  - [thermorawfileparser/\*.mzML](#spectra)
link doesnt work!?

2022-03-31 11:02 UTC, d4straub commented on docs/usage.md
> +nextflow run nf-core/quantms --input '/url/path/to/your/experimentX_design.tsv' --database '/url/path/to/your/proteindatabase.fasta' -profile docker
outdir?

2022-03-31 11:05 UTC, d4straub commented on modules/local/librarygeneration/main.nf
> +        DIA-NN: 1.8.0
better not hardcode versions, if possible!

2022-03-31 11:06 UTC, d4straub commented on modules/local/librarygeneration/meta.yml
> +name: librarygeneration
for local modules are no meta.yml required. Of course its nice, but when you have that, why not adding the module to nf-core/modules?

2022-03-31 11:12 UTC, d4straub commented
Apart from comments above, Markdown & YAML tests are still required but not executed (change in template 2.3.x). Go here in github to settings > branches > Branch protection rules "Edit" > below "Status checks that are required." remove outdated tests and add as many actual ones as possible, i.e. all you test profiles.

2022-03-31 12:14 UTC, jpfeuffer commented on CHANGELOG.md
> +- First pipeline for DIA-LFQ data analsysis
Oh yes, we should follow this more closely. I was actually thinking about adding an auto-changelog based on PRs.
I think it is not critical for the first release and relatively hard to do retroactively. But I agree in general.

2022-03-31 12:15 UTC, jpfeuffer commented on README.md
> +   nextflow run nf-core/quantms -profile <docker/singularity/podman/shifter/charliecloud/conda/institute> --input project.sdrf.tsv --database database.fasta
thanks! weird that those slipped through the template update merge.

2022-03-31 12:16 UTC, jpfeuffer commented on conf/test_dia.config
> +    config_profile_description = 'Minimal test dataset to check pipeline function'
yep. true. will change

2022-03-31 12:59 UTC, jpfeuffer commented on README.md
> +DDA-LFQ:
oh yes, this is cool. maybe we will find time. how was this created?
Can we reuse a template?

2022-03-31 15:47 UTC, jpfeuffer commented on modules/local/librarygeneration/main.nf
> +        DIA-NN: 1.8.0
@daichengxin How do we get the version from that tool?

2022-04-01 07:26 UTC, d4straub commented on nextflow.config
>      outdir                     = './results'
To elaborate: When running the pipelines in the cloud it can happen that with default (i.e. outdir = ./results) the results folder is on a remote and later auto-deleted instance and therefore never can be obtained. Thats why outdir is now required to be specified instead of having a default.

2022-04-01 13:42 UTC, jpfeuffer commented on modules/local/librarygeneration/meta.yml
> +name: librarygeneration
That is indeed a middle-term goal. We are basically missing module tests, otherwise, we tried to adhere to nf-core standards. Some of the modules also need a bit of refactoring to have fewer hardcoded parameters.

2022-04-01 14:47 UTC, jpfeuffer commented on conf/test_dia.config
> + *   nextflow run nf-core/quantms -profile test,<docker/singularity/podman>
But if I put outdir = xyz, then specifying outdir on the command line is optional, right? I specified it like this now.

2022-04-01 20:37 UTC, ewels commented
Done and done ✅ 

Sorry, need to get around to updating the website function that we have to set all repo settings...

2022-04-02 08:49 UTC, ypriverol commented
@daichengxin can you tackle the comments done by @d4straub

2022-04-02 09:00 UTC, jpfeuffer commented
I already did. Please wait

2022-04-18 07:35 UTC, ypriverol commented
@jpfeuffer @daichengxin the tests are failing here: 
```
2022-04-18T07:32:53.3378344Z  -- Check script './workflows/./../subworkflows/local/../../modules/local/openms/idfilter/main.nf' at line: 2 or see '.nextflow.log' file for more details
2022-04-18T07:32:53.3900334Z -[0;35m[nf-core/quantms][0;31m Pipeline completed with errors[0m-
2022-04-18T07:32:54.4094367Z WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
2022-04-18T07:32:54.5082665Z ##[error]Process completed with exit code 1.
20```

2022-04-18 07:46 UTC, daichengxin commented
It has been restored in bigbio branch.

2022-04-20 08:03 UTC, d4straub commented on README.md
> +DDA-LFQ:
The figure can be found [here](https://github.com/nf-core/eager/blob/master/docs/images/usage/eager2_metromap_complex.svg) and can be used as template I guess. Use a vector graphics software such as inkscape to modify. Remember to acknowledge the original figure in case you use it as template.

2022-04-20 08:10 UTC, d4straub commented on README.md
> +DDA-LFQ:
Oh just now I see you actually added a metro map, cool!

2022-04-20 08:12 UTC, d4straub commented on docs/output.md
> +  - [thermorawfileparser/\*.mzML](#spectra)
Tried again and works, so solved.

2022-04-20 08:20 UTC, d4straub reviewed
Looks good to me, but tests are still making trouble, see https://github.com/nf-core/quantms/runs/6083013950?check_suite_focus=true

1. Is this multiple warning intended?

> WARN: Label: 'label free sample'
WARN: Label: 'label free sample'
WARN: Label: 'label free sample'
WARN: Label: 'label free sample'

2. An output file is missing:

>  Error executing process > 'NFCORE_QUANTMS:QUANTMS:FILE_PREPARATION:THERMORAWFILEPARSER (SF_200217_pPeptideLibrary_pool1_HCDOT_rep1)'
Caused by:
  Missing output file(s) `*.mzML` expected by process `NFCORE_QUANTMS:QUANTMS:FILE_PREPARATION:THERMORAWFILEPARSER (SF_200217_pPeptideLibrary_pool1_HCDOT_rep1)`

If you do not immediately have an idea what went wrong there I suggest running `-profile test_localize` locally and troubleshoot there.

2022-04-20 08:42 UTC, jpfeuffer commented
Yes we have these hiccups from time to time downloading the data. We will move them to an FTP under our control and at the same time tell the public database to fix it if possible.

Yes the debug statements can go I think. Or switched to log.debug

2022-04-20 12:45 UTC, jpfeuffer commented
Done.

2022-04-20 13:14 UTC, d4straub approved these changes
Great, all tests pass again, congrats!

Unfortunately there are still warnings in tests that are not very nice, in `test_lfq`:

> WARN: There's no process matching config selector: NFCORE_QUANTMS:QUANTMS:.*:ID:PSMRESCORING:EXTRACTPSMFEATURES
WARN: There's no process matching config selector: NFCORE_QUANTMS:QUANTMS:.*:ID:PSMRESCORING:PERCOLATOR``

`test_localize`:

> WARN: There's no process matching config selector: NFCORE_QUANTMS:QUANTMS:.*:ID:PSMFDRCONTROL:IDSCORESWITCHER

Anyway, all my concerns were addressed so I give my approval. You'll need a second one for this PR (because its into master, into dev is only 1 review needed).

2022-04-20 13:26 UTC, ypriverol commented on nextflow.config
> +    add_decoys               = false
@jpfeuffer should we make add_decoys default = true. Because most of the users, I guess will start with the uniprot protein database.

2022-04-20 13:31 UTC, ypriverol commented on CHANGELOG.md
> +
@jpfeuffer should we add here msstats also, because is already included in the pipeline.

2022-04-20 13:32 UTC, ypriverol requested changes
Minor changes has been included.

2022-04-20 13:36 UTC, jpfeuffer commented on nextflow.config
> +    add_decoys               = false
I agree with that but on the other hand, it is currently more dangerous if you add decoys to a database that already has decoys. You currently do not get errors, just wrong results.
On the other hand you get an errors if decoys are completely missing.

2022-04-20 13:38 UTC, ypriverol commented on nextflow.config
> +    add_decoys               = false
But they have a step that they will see decoys has been added. No? They will clearly see that decoys are getting added.

2022-04-20 14:04 UTC, jpfeuffer commented on nextflow.config
> +    add_decoys               = false
But what if they don't know that there were decoys inside already. Then they just get nonsense results and complain here. And we have to figure out what was wrong in the first place. So I prefer them to make a conscious choice about adding decoys (e.g. after getting an error about missing decoys).

2022-04-20 14:09 UTC, jpfeuffer commented on nextflow.config
> +    add_decoys               = false
We just got a PR about that: https://github.com/OpenMS/OpenMS/issues/4917 let's fix that later and keep that default for now.

2022-04-20 14:16 UTC, jpfeuffer commented on CHANGELOG.md
> +
did you upgrade dia-nn already for this release?

2022-04-20 14:18 UTC, ypriverol commented on CHANGELOG.md
> +
yes, it is 1.8.1

2022-04-20 14:58 UTC, ypriverol approved these changes

2022-04-21 09:58 UTC, merged