Dev release 1.1.1
nf-core/quantms pull request #95
Opened 2023-03-26 08:23 UTC by ypriverol

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-03-26 09:12 UTC, ypriverol commented
@fabianegli suggested doing a release 1.1.1 including the  following fixs: 
- changes in Comet version to 2023
- bug fixing from @sminot about container resolve in AWS. (https://github.com/nf-core/quantms/pull/93)
- Zenodo accession in README. 
- MicroMamba for CI/CD.

2023-03-26 09:25 UTC, jpfeuffer requested changes

2023-03-26 09:25 UTC, jpfeuffer commented on CHANGELOG.md
> +## [1.2.0] nfcore/quantms - [TBD] - Thimphu
Shouldn't this be 1.1.1?
I think it doesn't hurt adding a small changelog for it.

- Updated Comet version.
- Improved output docs for mzTab
- Added dev profile for nightly versions of OpenMS tools
- Fixed bug in docker vs. singularity container logic in some processes.

2023-03-26 09:25 UTC, jpfeuffer commented
Yes please combine with my suggestion s

2023-03-26 09:28 UTC, ypriverol commented on CHANGELOG.md
> +## [1.2.0] nfcore/quantms - [TBD] - Thimphu
@jpfeuffer this is a minor update, and bug fix, then probably 1.1.1 looks more appropriate no? My point is, the previous 1.1.0 is really a major compare with 1.0.0.

2023-03-26 09:31 UTC, ypriverol commented on CHANGELOG.md
> +## [1.2.0] nfcore/quantms - [TBD] - Thimphu
Sorry, I misunderstood your comment. You are right.

2023-03-27 08:25 UTC, fabianegli requested changes
Apart form the small changes, it is ready for release.

2023-03-27 08:25 UTC, fabianegli commented on nextflow.config
> +    version         = '1.1.1dev'
We're getting ready for the release, so it makes sense now to set the release version.

2023-03-27 09:41 UTC, jpfeuffer approved these changes

2023-03-27 09:43 UTC, fabianegli approved these changes

2023-03-27 10:21 UTC, merged